export class Spot {
    nr: number = 0;
    call: string = "";
    freq: number = 0;
    dxcall: string = "";
    comment: string = "";
    time: string = "";
    band: number = 0;
    dxPrefix: string = "";
    dxName: string = "";
    dxCqz: string = "";
    dxItuz: string = "";
    dxCont: string = "";
    dxLong: string = "";
    dxLat: string = "";
    spotterPrefix: string = "";
    spotterName: string = "";
    spotterCqz: string = "";
    spotterItuz: string = "";
    spotterCont: string = "";
    spotterLong: string = "";
    spotterLat: string = "";
}